### ISSUE TITLE
(Minor) Simple Slavery ++ compatibility

### ISSUE THREAD

**Issue by IHateMyKite** [IHateMyKite/UnforgivingDevices#10]
Issue: When being sent to auction from SS++, it will cause to break a game in some way (infinite black screen for me when auction end). Investigation is needed. From some fast tests, it looks like the devices are unlocked properly.

Reports:
[https://www.loverslab.com/topic/148601-simple-slavery-plus-plus/?do=findComment&comment=3699823](https://www.loverslab.com/topic/148601-simple-slavery-plus-plus/?do=findComment&comment=3699823)

**Comment by BreadDain** [comment]
Report invalidated in one run. Simple Slavery 6.3.14, slavery outcome: Cursed Collar quest from Deviously Cursed Loot, was wearing Abadon Restrictive set with plug and belt. Scene got processed as expected (with minor issue, see below), all items were stripped beside plug (expected, quest item), slavery quest ended and character got loaded near Riften with collar equipped.

Minor issues/compatibility suggestion:
Vibrations/horny/orgasm idles conflict with SS bound idles (on the stage), suggesting to hang any onUpdate and orgasm loop processing between SSLV Entry and SSLV Exit events, they mark full mod scene.

**Comment by IHateMyKite** [comment]
Tr yid it and didn't find issue anymore. I don't think the animation bug is that much of an issue. May make a new issue ticket later, for now I'm closing this.
