### ISSUE TITLE
(Minor) DeviousLore compatibility check

### ISSUE THREAD

**Issue by IHateMyKite** [IHateMyKite/UnforgivingDevices#11]
Post: [https://www.loverslab.com/topic/165197-unforgiving-devices/?do=findComment&comment=3725003](https://www.loverslab.com/topic/165197-unforgiving-devices/?do=findComment&comment=3725003)

New DeviousLore possibly makes UD incompatible. Investigation is needed. Only way for it to break the mod is by either changing how devices are transferred or by overwriting the devices.

**Comment by BreadDain** [comment]
Devices records are overwritten, Editor ID is changed for most if not all of devices within Devious Devices Lore patch plugin

**Comment by IHateMyKite** [comment]
I don't understand the reason behind it. Anyway, I can technically just patch the patch. This will just patch the device with edited editorID.

**Comment by IHateMyKite** [comment]
Didn't manage to make the patch. Looks like there is nothing to do about this. Will keep this mode as incompatible. Closing.
