### ISSUE TITLE
(Minor) List of wrong device parameters.

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#12]
steel padded arm/leg cuffs, black leather arm/leg cuffs - mod counts as generic device type but are Cuffs
fetters (all of them?) - generic, but are leg cuffs
iron ballet boots (normal, not reinforced ones) - no lockpicking is possible, can't be struggled from
Iron chain harness (Legs) - generic, but are cuffs

Iron chain harness - counts as belt, but is full body restraint. Maybe counting it as belt is correct though.
Iron chain harness (Bra) - prevents equipping any type of nipple piercings while visibly device doesn't block that area.

**Comment by IHateMyKite** [comment]
Which patch do you use?

**Comment by BreadDain** [comment]
DD 5.1 + BRRF

**Comment by IHateMyKite** [comment]
Looks like only 5.1 patches have this issue, Perhaps I forget to re-patch them with new patching script. Only For Him (without BRRF) patch is Ok because I did it recently.

**Comment by IHateMyKite** [comment]
Hopefully fixed the issue
