### ISSUE TITLE
Special button interaction with crits

### ISSUE THREAD

**Issue by IHateMyKite** [IHateMyKite/UnforgivingDevices#120]
**Describe the bug**
[A clear and concise description of what the bug is.](https://www.loverslab.com/topic/165197-unforgiving-devices/?do=findComment&comment=3990632)

**To Reproduce**
https://www.loverslab.com/topic/165197-unforgiving-devices/?do=findComment&comment=3990632

**Expected behavior**
Pressing special button while crit is on (widget flashes, shader is applied) should not count as crit failure

**Comment by Zaflis** [comment]
In further testing it might have been just timing issue being too strict. I increased the crit time tolerance in MCM and it has resulted in more successful crits with devices that previously had issues. Maybe the MCM's range could also be increased even more, although i wouldn't need it i don't know if someone else does. I already use its current maximum limit.

**Comment by IHateMyKite** [comment]
I was testing it for some time and didn't manage to reproduce the issue. But I'm using SE with Papyrus NG which makes scripts very fast so maybe that is why
