### ISSUE TITLE
Mini-game duration adjustments

### ISSUE THREAD

**Issue by iiw2012** [IHateMyKite/UnforgivingDevices#121]
This is a subjective matter but it seems to me that the mini-game ends very quickly (especially when the player is a low level).

#### Suggestion
I took a quick look in the MCM and didn't find a way to adjust the duration of the mini-game. It won't be bad if there will be such an option.

Another suggestion is to add a little time at the start of the mini-game during which the stats don't decrease. Literally 2-3 seconds for the player to get ready.

**Comment by IHateMyKite** [comment]
Adjusting the minigame duration is not currently available. How long minigame lasts depends directly on device, minigame and actor stats (more stats means longer minigame). 
As you assigned yourself, I'm taking as that you want to work on it yourself. In that case, the best place to change how much stats are drained is [there](https://github.com/IHateMyKite/UnforgivingDevices/blob/9812425a1bc17ae30600e082bc4e90dc3a984edd/Scripts/Source/UD_CustomDevice_RenderScript.psc#L5391-L5393) and [there](https://github.com/IHateMyKite/UnforgivingDevices/blob/9812425a1bc17ae30600e082bc4e90dc3a984edd/Scripts/Source/UD_CustomDevice_RenderScript.psc#L5424-L5426). Multiplying the values with new float MCM value should be enough. If it will be 0.5, the minigame will be generally 2x longer, etc.. But the stats decreased will be same, so it might be also good idea to reduce dps.

Bonus: The function ProccesAV and ProccesAVHelper is called on every minigame tick. So it might be good idea to move loc_xxxDrain value to outside the function, and only update them once per second. Reason is that the values UD_minigame_xxx_drain are bitcoded, and need to be decoded first before they are assigned to local variable. The decoding part is quite slow in comparison to direct access, so moving it a bigger update task might increase performance without (hopefully) breaking something. If you don't want to do this part, I will do it. Just found it by chance, so I had to write it down.

**Comment by iiw2012** [comment]
Yep, my idea was to add multiplier to the ProccesAV and ProccesAVHelper function. I suppose that should be suffice since I dont want to overcomplicate things.

As for the starting "free" period, I still thinking about it. It could be some global timer with disabling mentioned function during first 2 seconds or so. I will do it, it is not that difficult, I hope :)

That issue is not that important to do deep reworking. Hasty mini-games only happen at the beginning of the game when the player is lucky enough to be in a relatively high level device. These are rare cases, but a little confusing when first introduced to the mod. I judge this from my own experience, when at first I did not understand what was happening at all :)

**Comment by IHateMyKite** [comment]
I was thinking about making the tutorial pop-ups, as in the vanilla game. It would pop-up every time minigame is played for the first time. I remember the native function for that existed, but I can't remember how was it called.

**Comment by IHateMyKite** [comment]
[Found it](https://www.creationkit.com/index.php?title=ShowAsHelpMessage_-_Message), its extended function for MessageBox script. Issue is that there will need to be message for every minigame. Alternatively, there is [this ](https://www.creationkit.com/index.php?title=ShowTutorialMenu)console command which could be used with COnsoleUtil

**Comment by iiw2012** [comment]
Great! I'll check it out!
