### ISSUE TITLE
Red Leather Blindfold (Custom) problem

### ISSUE THREAD

**Issue by kurotatsu77** [IHateMyKite/UnforgivingDevices#123]
**Describe the bug**
DD BRRF For Him patch problem.
Device in question is Red Leather Blindfold (Custom)
Looks like there's some errors in patching it, as it's not being registered for device manipulation. When clicked in inventory it produces UD struggle dialogue instead of top-level UD dialogue with options for Details etc. Also even after successful struggle out it fails to be removed. This is long-standing issue, which I forgot to report and confirmed to be present in the latest UD beta 2.1.
All other custom blindfolds, leather and ebonite are working as they should.

**To Reproduce**
1. Acquire Red Leather Blindfold (Custom)
2. Wear it
3. Observe it not appearing on the device menu called via holding "." button
4. Click it in inventory and observe getting UD struggle dialogue instead of top-level UD dialogue

**Expected behavior**
It should work same as all other custom blindfolds.

**Desktop (please complete the following information):**
LE, UD Beta 2.1

**Additional context**
Do we have separate repository for the patches like DD, DCL, etc? If not - maybe create, so I can try to make PR there to address this and other issues?

**Comment by IHateMyKite** [comment]
Created new [repository ](https://github.com/IHateMyKite/UnforgivingDevices_FOMOD) for FOMOD. This repo also contains all patches which are available in fomod. You can copy the issue there, and create PR if you want. I will probably also later add there the pascal scripts for xEdit

**Comment by kurotatsu77** [comment]
OK, I think I found the source of problem, it's actually in the DD itself!
![image](https://user-images.githubusercontent.com/117896156/216954846-dd63f19f-a0a5-4e45-8825-d0a4d6d97239.png)

**Comment by IHateMyKite** [comment]
In that case, it might be good idea to report in in DD thread, so they can fix it before 5.2 release

**Comment by kurotatsu77** [comment]
Done!
