### ISSUE TITLE
Laura's Bondage Shop, Sirrinas Yoke not unlockable.

### ISSUE THREAD

**Issue by GTAVC** [IHateMyKite/UnforgivingDevices#127]
**Describe the bug**
When playing through Lauras Bondage Shop, the player gets an Item called "Sirrina's Yoke".
According to its description, it is only unlockable with its special key: "Sirrina's Key".
The Item information states the correct key, but there is no lock to open, the Item has zero locks.
It can only be unlocked with the debug menu of UD.

**To Reproduce**
1. Get Sirrina's Yoke and equip it. Laura's questline is not needed for that.
2. Get Sirrina's Key
3. Try to unlock it - no option shown.
4. Check Item information and find correct key, but zero locks to open.

**Expected behavior**
Using the key to open the yoke. Lockpicking should not be possible.

**Additional context**
Version Unforgiving.Devices.2.1 
Skyrim AE up to date steam version.

**Comment by Zaflis** [comment]
I too had issue with that, forgot to report.

**Comment by IHateMyKite** [comment]
Strange, will have to take a look at the patcher again. This issue made me also remember that I will have to add some array which will store all generic keys, so the quest keys (like Sirrina's Key) can't get destroyed

**Comment by IHateMyKite** [comment]
Fixed in FOMOD repo. Closing
