### ISSUE TITLE
When piercings/plugs trigger animation, DD contraption disappears

### ISSUE THREAD

**Issue by Zaflis** [IHateMyKite/UnforgivingDevices#130]
**To Reproduce**
1. Equip 2 grand plugs and 2 soulgem piercings.
2. Enter DD contraption from Cursed Loot for example in any town.
3. Wait for O meter to fill, animation start and end.
4. Player doesn't re-enter the contraption which has now vanished.

**Expected behavior**
Animation shouldn't attempt to start when in contraption.
Even if you did want to use contraption specific struggle animation you would have to make sure it ends properly then. It might be easier to not start one at all like when in combat.

**Versions**
- UD nightly build 11.3.2023.
- DD 5.2 for Skyrim SE, DCL 9.

**Comment by IHateMyKite** [comment]
Thank you for report. I totally forget to add any check for contraptions, as I barely encounter it in game. Because of that I didn!t have much opportunities to test it. Adding check which prevent animation when actor is in contraption should be hopefully easy.
