### ISSUE TITLE
Something triggers horny animation without proper filtering

### ISSUE THREAD

**Issue by iiw2012** [IHateMyKite/UnforgivingDevices#131]
**Description**

Something triggers animations on the player without proper consideration for heavy bondage. That is, the player's hands are free, and the animation is played like actor wears yoke or armbinder.

According to the logs, some mod calls the **StartSoloAnimation** function for an animation that is not suitable for the current state of the player. The only place where such a call is possible is in here:
https://github.com/IHateMyKite/UnforgivingDevices/blob/50b4ca2ab5e75b93c774ad9a33565c161a33ec1f/Scripts/Source/zadlibs_UDPatch.psc#L751-L758

**To Reproduce**
1. Get into heavy bondage with a lot of vibrators.
2. (probably) Wait for the horny animation triggered by the unknown mod. Not sure if vibrator(s) should be turned on.
3. Remove heavy bondage.
4. Wait again for the horny animation triggered by the unknown mod.
5. This animation will look like the player is still in HB.

**Expected behavior**
Animations should correctly take into account the player's HB.

**Additional context**
Found on the latest version of 2023-03-12.
Checked with DD 5.2 beta 10 and DD 5.2.
<details>
  <summary>List of mods:</summary>

```
Skyrim.esm
Update.esm
Dawnguard.esm
HearthFires.esm
Dragonborn.esm
ccBGSSSE001-Fish.esm
ccQDRSSE001-SurvivalMode.esl
ccBGSSSE037-Curios.esl
ccBGSSSE025-AdvDSGS.esm
Unofficial Skyrim Special Edition Patch.esp
SexLab.esm
Devious Devices - Assets.esm
SexLabAroused.esm
Devious Devices - Integration.esm
Devious Devices - Expansion.esm
Devious Devices - Contraptions.esm
Schlongs of Skyrim - Core.esm
Expressive Facegen Morphs.esl
iWant Widgets.esl
ZaZAnimationPack.esm
SkyUI_SE.esp
UnforgivingDevices.esp
UnforgivingDevices - DD Patch.esp
Devious Devices SE patch.esp
Customizable Camera.esp
FNIS.esp
CBBE.esp
3BBB.esp
SOSPhysicsManager.esp
FemaleOutfitReplacer.esp
12FemaleBrows.esp
SLAnimLoader.esp
NibblesAnimObjects.esp
SLAL_AnimationsByLeito.esp
SLAL_AnimationByBakaFactory.esp
Schlongs of Skyrim.esp
SLALAnimObjBillyy.esp
FNISSexyMove.esp
RaceMenu.esp
XPMSE.esp
RaceMenuPlugin.esp
RaceMenuMorphsCBBE.esp
PR113_InterfaceWidgets.esp
KSHairdosSMP.esp
The Eyes Of Beauty - Elves Edition.esp
TheEyesOfBeauty.esp
UIExtensions.esp
widescreen_skyui_fix.esp
Alternate Start - Live Another Life.esp
```

</details>

**Comment by iiw2012** [comment]
The problem was not where I expected.

https://github.com/IHateMyKite/UnforgivingDevices/blob/50b4ca2ab5e75b93c774ad9a33565c161a33ec1f/Scripts/Source/UD_CustomDevice_NPCSlot.psc#L2197-L2206

**Comment by IHateMyKite** [comment]
So, the issue is cache ?

**Comment by iiw2012** [comment]
Yes. For now, I just removed all update conditions. This should not create performance issues.

There is room for improvement. Updates to animation caches are required in other places, and so far I've done it locally, with arguments passing through callstack and it looks ugly.

https://github.com/IHateMyKite/UnforgivingDevices/blob/e202d22a51d04c97d96bddb4f50278eb54b4146e/Scripts/Source/UD_AnimationManagerScript.psc#L756-L772

In general, the animation cache should be updated when
1. The result of the **GetActorConstraintsInt** function for the actor has changed.
https://github.com/IHateMyKite/UnforgivingDevices/blob/e202d22a51d04c97d96bddb4f50278eb54b4146e/Scripts/Source/UD_AnimationManagerScript.psc#L939
3. The list of loaded json files has changed.
4. Game has loaded (just in case).

It may be possible to implement a centralized system to detect changes in the actor's equipment. Based on the UD_CustomDevice_NPCSlot class for example. But I have not yet figured out how reliable this can be done.

**Comment by iiw2012** [comment]
Not clear enough :(.

In short, the problem of updating animation caches comes down to checking the result of the **GetActorConstraintsInt** function. But this function is heavy to execute (around 100-150ms on SSE).

The result of this function is already cached in the "UD_ActorConstraintsInt" variable for each actor, but is of limited use. https://github.com/IHateMyKite/UnforgivingDevices/blob/e202d22a51d04c97d96bddb4f50278eb54b4146e/Scripts/Source/UD_AnimationManagerScript.psc#L948

If there is a reliable mechanism to update the value of the UD_ActorConstraintsInt variable in a timely manner, then the animation cache can be used more efficiently. Not to mention the overall increase in speed, due to the reduction in the number of **GetActorConstraintsInt** calls.

**Comment by IHateMyKite** [comment]
I thing it might be better to just update the constraints only if there is either lock or unlock operation. But currently there are no such UD events, only the DD ones, but they are quite limited. I will first add new events which will fire up when device is locked/unlocked. Then the NPC slot can just be registered for the events and update the constraints. There will then need to be some kind of time delay, so if multiple lock operations happen at once, only the last event will be used.

**Comment by iiw2012** [comment]
I'm trying different changes in a new branch.
https://github.com/iiw2012/UnforgivingDevices/tree/animation-fixes-01

So far, I've changed GetActorConstraintsInt to use the cached value by default. And added explicit updates:
1. In the **startScript** and **endScript** functions of **UDCustomDeviceMain**.
2. Before starting mini-games.
3. In **zadlibs_UDPatch** when requesting a list of animations.
4. In **UD_CustomDevice_NPCSlot**

Now all calls to this function without a cache are made explicitly.

But if **GetActorConstraintsInt** is used outside that cases then its cached value could be wrong. For example, for the NPCs not registered in UD.
