### ISSUE TITLE
Regarding the ability to ESLify the different patches

### ISSUE THREAD

**Issue by Ethryan** [IHateMyKite/UnforgivingDevices#139]
**Is your feature request related to a problem? Please describe.**
Will the different patches be changed into the ESPFE format to save space in the modlist?

**Describe the solution you'd like**
Compacting the <ins>**2**</ins> records needed in **UnforgivingDevices - DD Patch.esp**.
Armor xx0012E5 zad_plugSoulgemInventory_AddedRenderDevice
Quest  xx0012E1 UD_PatchQuest_DD
**UnforgivingDevices - DCL Patch.esp** - No records need editing.
Compacting the <ins>**1**</ins> record needed in **UnforgivingDevices - LBS Patch.esp**.
Quest  xx0012E0 UD_PatchQuest_LBS
And converting them to the ESPFE format.

That way they don't take up space in the modlist. Since they don't add any new Cells it should be possible. Unless scripts block this somehow.

**Comment by Ethryan** [comment]
Ok, i will eslify the patches tomorrow and then see if they work.

**Comment by IHateMyKite** [comment]
Works without issue. Even on existing save. Only issue is that the esl is not supported by LE (I think), so I will have to add more fomod options so LE users can still choose esp

**Comment by Ethryan** [comment]
I made a CACO patch too in that issue

**Comment by Ethryan** [comment]
For LE, i think the only thing you have to do is to untick the ESL Record Flag in the File Header of the mod, I use SSEEdit, that way you can keep the same FormID Records for both versions.

**Comment by IHateMyKite** [comment]
According to this article, it should be no possible https://dyndolod.info/Messages/Plugin-Limit

**Comment by Ethryan** [comment]
That's why i said you could untick the esl record flag for LE, ESL is only a flag that tells Skyrim SE how to handle the file. If you untick it it should work on LE again.

**Comment by Ethryan** [comment]
![image](https://user-images.githubusercontent.com/3237986/230142816-301cae1d-cde8-4639-b9f3-54416d1b0c36.png)

and then
![image](https://user-images.githubusercontent.com/3237986/230142993-11b97d61-296d-4b7c-a0bb-8cdff8c6c476.png)

That toggles it between an eslified file and a normal esp file

**Comment by IHateMyKite** [comment]
I understand, but what I mean is that if user will be selecting the patches, they should be able to choose both options, as I doubt some users would want to open the xEdit just to esl the patch.

**Comment by Ethryan** [comment]
Ah, ok

**Comment by Ethryan** [comment]
It works fine and installs in MO.
