### ISSUE TITLE
Minigame bug with menus.

### ISSUE THREAD

**Issue by Ethryan** [IHateMyKite/UnforgivingDevices#147]
**Describe the bug**
A issue where all skyui menus gets locked up after finishing a cut or struggle minigame. My guess is that it somehow considers the minigame as still ongoing and thus keeps the menus locked.

**To Reproduce**
1. Go to ‘A Device controlled by UD’.
2. Click on 'Click on struggle or cut'.
3.   'Play the minigame until you run out of stamina’.
4. See error where all menus are locked.

**Expected behavior**
I expected the skyui item, magic and tab menus to be available after a finished minigame.

**version:**
Latest prerelease 2.1b3.

**Additional context**
Just a thought, but how does the minigame script handle the infinite stamina of tgm mode. I was testing some things and might have left it enabled.

**Comment by IHateMyKite** [comment]
Can't reproduce. Working for me as intended. Do you have some mod which change the UI ? Also, if you have papyrus NG, update it to last version, as the older version were not that safe, and were causing issues with various things (UI included)
Also_
What device did you try it on ? Did you have hardcore mod enabled ? Can you check your character current magic effect factions and see if it has Bussy/Disable faction from UD ?

**Comment by Ethryan** [comment]
Gonna try to reproduce and see if i i can get it in a save to check.

**Comment by Ethryan** [comment]
[Stuck save.zip](https://github.com/IHateMyKite/UnforgivingDevices/files/11295445/Stuck.save.zip)
I found 1 save that i took in the middle of when it was stuck.
And i had hardcocore mode disabled.

**Comment by IHateMyKite** [comment]
Only issue I found is this 
![pic](https://user-images.githubusercontent.com/103142567/233667833-caacd962-b7bc-4877-af32-e74f7bdc7d2d.png)
Dunno if its related to your issue tho.  Please, check with console if the actor is in faction. 
Try to type this and see what it returns: player.getfactionrank UD_Bussy_Faction

**Comment by IHateMyKite** [comment]
There are some differences, but I would need one more where it doesn't work to get some relevant data. For now I have some more question so I have something to work with

- Did you make new game ? Or was it on existing save. Don't thing that can cause issue, but better ask
- After the bug happens, does it ever fix itself ? I have similiar problem once in the while, where after minigame ends, it doesn't allow to open menus. But after some time, it always fix itself. Try to use cmd and type _enableplayercontrols_. I'm quite certain that will fix issue, but quastion is what is causing it.
- You have many active scripts and some suspended (even when it works). Its possible that some mod you are using is causing such heavy load that in combination with UD, it will suspend whole engine. You can try papyrus profiler (either internal or external from nexus) to see what is causing biggest load

**Comment by Ethryan** [comment]
> There are some differences, but I would need one more where it doesn't work to get some relevant data. For now I have some more question so I have something to work with


> * Did you make new game ? Or was it on existing save. Don't think that can cause issue, but better ask

New game

> * After the bug happens, does it ever fix itself ? I have similiar problem once in the while, where after minigame ends, it doesn't allow opening menus. But after some time, it always fixes itself. Try to use cmd and type _enableplayercontrols_. I'm quite certain that will fix the issue, but the question is what is causing it.

It don't restore access i waited 5 min just in case.

> * You have many active scripts and some suspended (even when it works). Its possible that some mod you are using is causing such heavy load that in combination with UD, it will suspend the whole engine. You can try papyrus profiler (either internal or external from nexus) to see what is causing the biggest load.

Gonna check it.

> * Can you provide papyrus log (with logging turned on)?

Hmm, i couldn't catch the log when I was testing around.

> Also, as you said you use Papyrus NG, you can try this config, it should much more increase the speed while still being safe. It should also allow more information in papyrus logs.
> 
> [PapyrusTweaks.zip](https://github.com/IHateMyKite/UnforgivingDevices/files/11298286/PapyrusTweaks.zip)

Gonna test this one in a NG and see if i can recreate the bug.

**Comment by Ethryan** [comment]
And i gave you a stuck save:

> [Stuck save.zip](https://github.com/IHateMyKite/UnforgivingDevices/files/11295445/Stuck.save.zip) I found 1 save that i took in the middle of when it was stuck. And i had hardcore mode disabled.

**Comment by IHateMyKite** [comment]
I know, but I will need at least one more, so I can more accurately filter out garbage, and see what is most likely causing the issue

**Comment by Ethryan** [comment]
Ok, will see if i can create a new one, will try tomorrow.

**Comment by Ethryan** [comment]
[new save.zip](https://github.com/IHateMyKite/UnforgivingDevices/files/11301304/new.save.zip)
A new save, with logs included.

**Comment by IHateMyKite** [comment]
One issue I see from your papyrus log is that there is some issue with DD dll.
`Unbound native function "FormHasKeywordString" called`
I have made recently [patch ](https://www.loverslab.com/topic/69936-devious-devices-framework-developmentbeta/?do=findComment&comment=4017930)for DD which allow DD to run without it. This pretty much means that there is no longer need to have separate version for AE and SE, as only difference between the two is the dll. After you install the patcdh, don't forget to remove the existing DeviousDevices.dll from folder SKSE\Plugins. If you use old dll, it can cause any kind of issue on engine level. Even one which results in the issue you have. Try it first and let me know if anything changes.

**Comment by IHateMyKite** [comment]
Also, I can only see warning/erros in the papyrus log. You have to enable the logging for UD in MCM setting. Its on Main page. Just change the Log Level to 3. That will cause quite a bunch of data to be dumped, so it might decrease the performance a little.

**Comment by Ethryan** [comment]
Ok, will do when i run into errors again.

**Comment by Ethryan** [comment]
Closing this, i spent the better part of 4 hours trying to get the error to repeat in a new save with logging on and debug enabled.

If someone else runs into this we can reopen and hopefully get more data so it can be fixed.
