### ISSUE TITLE
Removal of unneeded property

### ISSUE THREAD

**Issue by kurotatsu77** [IHateMyKite/UnforgivingDevices#162]
In the UDCustomDeviceMain.psc there's property definition:

Package Property NPCDisablePackage Hidden
    Package Function Get()
        return libs.SexLab.Config.DoNothing
    EndFunction
EndProperty

I believe it's not used and was added as experiment around 5 months ago. This can be seen as unneeded pry into the inner parts of SexLab. In fact it's proven to cause incompatibility with Scrab's P+.
Maybe it's better to remove this?

Didn't wanted to make PR just for this change, and also maybe I've missed something and it's really needed...

**Comment by iiw2012** [comment]
It looks like that property is not used anywhere. UD has its own copy of DoNothing package, which is set in `UnforgivingDevicesMain.UD_NPCDisablePackage`.

**Comment by IHateMyKite** [comment]
The property is truly unused. I will remove it with #161
