### ISSUE TITLE
Abadon Plug escape minigame glitch

### ISSUE THREAD

**Issue by kurotatsu77** [IHateMyKite/UnforgivingDevices#166]
**Describe the bug**
If Abadon Plug is in Random Edging mode and paused, remove minigame does not consumes stamina and no crits happens.
UD version with bug confirmed is 2.1b5.

**To Reproduce**
1. Wear Abadon Plug
2. Get to point where you can try to remove it
3. When it's activated check it's Vib. Details, it needs to be in Random Edge mode
4. Stop escape and wait for it to reach edge and pause it's vibrations
5. Start escape again and observe that stamina is not being depleted, pressing S key reduces it's condition as it should, but no crits happen. When Plug unpauses it's vibrations - observe minigame working correctly until it's paused again.

**Expected behavior**
Minigame should work with both paused and unpaused Random Edge vibrations.

**Comment by IHateMyKite** [comment]
Looks like I have found the source of issue. I have implemented the function isPaused on vibrator script. Issue is that the exact same function exist on base script, so all vibrators had the method overridden, Basically, if the vibration were paused, the device was thinking that the minigame was paused too. I will just have to rename the function.
