### ISSUE TITLE
iWW reacts to NPCs

### ISSUE THREAD

**Issue by kurotatsu77** [IHateMyKite/UnforgivingDevices#167]
**Describe the bug**
Orgasm widget flashes when NPC orgasms.
Confirmed on UD version 2.1b5.

**To Reproduce**
1. Go to place where at least on NPC with bunch of vibrators present
2. Make sure NPC is registered, auto works fine
3. Make player orgasm to make orgasm widget appear
4. Stand still and wait for NPC to orgasm, when they do - player's widget flashes

**Expected behavior**
Widget should react only to player's orgasms.

**Additional context**
I think something similar happens to vibrators widgets too, maybe they should be checked, just in case. Assigning to iiw2012, because he knows this system the best, I believe.

**Comment by IHateMyKite** [comment]
Found the source of issue, which is caused by [this](https://github.com/IHateMyKite/UnforgivingDevices/blob/4b70a00265b640e57625296c782c85aaf9f5856c/Scripts/Source/UD_OrgasmManager.psc#L946) part not being exclusive for player. Will again fix with #165.
