### ISSUE TITLE
Unexpected behavior of vibrators after loading the game

### ISSUE THREAD

**Issue by iiw2012** [IHateMyKite/UnforgivingDevices#169]
**Describe the bug**

After loading the game some vibrators break down. For example, vibrators in "edge mode" gets wild and won't stop. Others may stop without any reason and so on.

**To Reproduce**

1. Equip vibrator in edge mode on the actor.
2. Wait for it to activate.
3. Save game.
4. Load game.
5. See what happened.

**Expected behavior**

Vibrator should continue working in its last mode.

**Additional context**

According to Resaver, vibrator somehow lost its value in `_currentVibRemainingDuration` after loading the game. This broke the conditions in the update routine, which led to unexpected behavior.

![vib-edge-bug-01](https://github.com/IHateMyKite/UnforgivingDevices/assets/110040088/090e381e-867a-4a8b-bb92-7765a6d8642a)

Here are saves taken before (Save18) and after (Save20) game load:

[Saves-vib-edge-bug-01.zip](https://github.com/IHateMyKite/UnforgivingDevices/files/11785493/Saves-vib-edge-bug-01.zip)

**Comment by IHateMyKite** [comment]
My guess is that it DD feature which turns off all plugs on save reload is the reason. On every game load, the [StopVibration ](https://github.com/IHateMyKite/UnforgivingDevices/blob/4b70a00265b640e57625296c782c85aaf9f5856c/Scripts/Source/zadlibs_UDPatch.psc#LL678C38-L678C38)function is called. Issue is how to know if its called normally, or on game load. The only solution would be to find the code which calls the function, and patch it.

**Comment by IHateMyKite** [comment]
I have look at it and the script calling it is zadBQ00, and specifically, function Maintenance() which is called on every reload. This script is not override by UD, so there is currently nothing I can do. But I had idea for some. This script also contains functions for starting sexlab animations. And as of now, there is some kind of issue with these animation and new sexlab p+. So my idea was to basically rework the function to make it correctly use saxlab API. There can also be some optimization added in dll plugin to make it work faster. But these changes will be quite big so I will do it in next release. Anyway, what you opinion ?

**Comment by iiw2012** [comment]
To be honest, I didn't expect such difficulties.

If you think that something can be improved in the work DD or UD, then I fully support it. And it's really better to hold on to big changes until the next version.

So far I can offer a quick (and ugly) fix for the `zadlibs_UDPatch`:

```papyrus

bool maintenance_called = false

; Globally enable periodic event processing.
; It is called only from zadBQ00::Maintenance()
Function EnableEventProcessing()
    If in == "Maintenance routine called"
        maintenance_called = True
    EndIf
    Parent.EnableEventProcessing()
EndFunction

; Stop vibration event on actor.
Function StopVibrating(actor akActor)
    If maintenance_called
        maintenance_called = False
        Return
    EndIf
    if akActor.WornHasKeyword(UDlibs.UnforgivingDevice) && UDCDmain.isRegistered(akActor)
        if UDmain.TraceAllowed()
            UDmain.Log("StopVibrating("+GetActorName(akActor)+") - using patched version: " + akActor)
        endif
        UDCDmain.StopAllVibrators(akActor)
        akActor.SetFactionRank(zadVibratorFaction, 0)
        akActor.RemoveFromFaction(zadVibratorFaction)
    else
        if UDmain.TraceAllowed()
            UDmain.Log("StopVibrating("+GetActorName(akActor)+") - using default version: " + akActor)
        endif
        parent.StopVibrating(akActor)
    endif
EndFunction
```

Or maybe don't touch this behavior at all. Let it be not a bug, but a feature.

**Comment by IHateMyKite** [comment]
> To be honest, I didn't expect such difficulties.
> 
> If you think that something can be improved in the DD or UD, then I fully support it. And it's really better to hold on to big changes until the next version.
> 
> So far I can offer a quick (and ugly) fix for the `zadlibs_UDPatch`:
> 
> ```papyrus-skyrim
> bool maintenance_called = false
> 
> ; Globally enable periodic event processing.
> ; It is called only from zadBQ00::Maintenance()
> Function EnableEventProcessing()
>     maintenance_called = True
>     Parent.EnableEventProcessing()
> EndFunction
> 
> ; Stop vibration event on actor.
> Function StopVibrating(actor akActor)
>     If maintenance_called
>         maintenance_called = False
>         Return
>     EndIf
>     if akActor.WornHasKeyword(UDlibs.UnforgivingDevice) && UDCDmain.isRegistered(akActor)
>         if UDmain.TraceAllowed()
>             UDmain.Log("StopVibrating("+GetActorName(akActor)+") - using patched version: " + akActor)
>         endif
>         UDCDmain.StopAllVibrators(akActor)
>         akActor.SetFactionRank(zadVibratorFaction, 0)
>         akActor.RemoveFromFaction(zadVibratorFaction)
>     else
>         if UDmain.TraceAllowed()
>             UDmain.Log("StopVibrating("+GetActorName(akActor)+") - using default version: " + akActor)
>         endif
>         parent.StopVibrating(akActor)
>     endif
> EndFunction
> ```
> 
> Or maybe don't touch this behavior at all. Let it be not a bug, but a feature.

I thing that for now, it will be best to wait for release. As I said before, this was basically feature in DD, so UD have only taken the feature over.  It might actually be easier to just ask Kimy if she can't add some kind of MCM toggle for this feature to the DD. But there might be some reason why it was added.

**Comment by IHateMyKite** [comment]
Closing this for now. Only possible thing I can do is to create patch in DDNG for base DD so user can select if they want vibrators to stop on game reload.
