### ISSUE TITLE
(Minor) Anal plug removal with chastity belt

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#17]
Description: can attempt removal of anal plug (black soulgem) while being belted with a full chastity belt (Steel Chastity Belt (Padded)). Not sure if wearing straitjacket is relevant. Plug accesibility 23%, expected 0.

Version of skyrim: SE
Version of mod: 2.0b9 commit https://github.com/IHateMyKite/UnforgivingDevices/commit/84d5fb1d26527d575db04faa64fc5b2df887538c
Used patches: DD+BRRF, DCL, LBS

**Comment by IHateMyKite** [comment]
This functionality is implemented [here](https://github.com/IHateMyKite/UnforgivingDevices/blob/84d5fb1d26527d575db04faa64fc5b2df887538c/Scripts/Source/UD_CustomPlug_RenderScript.psc#L93-L99). You can give it a look if you have time.

**Comment by BreadDain** [comment]
Found the cause, yes, straitjacket was 100% relevant. [This check](https://github.com/IHateMyKite/UnforgivingDevices/blob/84d5fb1d26527d575db04faa64fc5b2df887538c/Scripts/Source/UDCustomDeviceMain.psc#L1696) is ablame, it is has a design flaw to check keyword that is not belt-specific:
![изображение](https://user-images.githubusercontent.com/30041703/164036251-15a622d8-9150-4579-b673-50f9c9f33d48.png)

Equipping the jacket fools the mod to think that belt is open because it runs keyword check on actor and not on belt reference.

**Comment by IHateMyKite** [comment]
In that case you can try adding somethink like this

```
Armor loc_belt = libs.GetWornRenderedDeviceByKeyword(getWearer(), libs.zad_DeviousBelt)
if loc_belt  
  if loc_belt.haskeyword(libs.zad_permitAnal)  
    ;Actor have belt which permits anal  
  else  
    ;Actor have belt which doesn't permit anal  
  endif  
endif  
```
