### ISSUE TITLE
Strange errors dropped when single trasnfers occur by Devious Strike

### ISSUE THREAD

**Issue by kurotatsu77** [IHateMyKite/UnforgivingDevices#175]
**Describe the bug**
https://www.loverslab.com/topic/165197-unforgiving-devices/page/69/#comment-4170033

Can confirm that single transfer fail with "render device = none" message, full transfers perform normally for me. 
This is true for UD 2.1 release. 
This was working with previous UD versions.

**To Reproduce**
1. Install Devious Strike mod
2. Find the strikers and engage them
3. Observe UD errors on single transfer

**Comment by kurotatsu77** [comment]
This potentially can be DD4 incompatibility, which is better to have prevented.

**Comment by IHateMyKite** [comment]
That should be not caused by UD. I only added check which prevent lock operation if passed ID is none. My guess is that Devious Strike sometimes call lock/unlock function with ID passed as none

**Comment by IHateMyKite** [comment]
That is correct, but the messages show that the Inventory device is none, not the RD
![20230828030334_1 jpg 48e7e688a89d2944920cc787a6f84ae0](https://github.com/IHateMyKite/UnforgivingDevices/assets/103142567/5d496a14-e7dd-4c31-bf74-5608eac39d20)

**Comment by kurotatsu77** [comment]
Interestingly enough, this is happening only at single transfer events, but transfer-all works as it should...

**Comment by IHateMyKite** [comment]
I will install last version of Devious Strike, and do some testing

**Comment by kurotatsu77** [comment]
Hmm, double-checked Devious Strike thread and indeed there are reports about single transfers not working on the latest version of it. So maybe indeed the problem is there, UD is so good that it able to properly report it. :D
Sorry for being stupid to bring it here...

**Comment by kurotatsu77** [comment]
Yep, it's problem in Devious Strike, there's function use which is not present in PapyrusUtil 3.3, so it's not working on LE and will not work without newer PapyrusUtil on SE.
