### ISSUE TITLE
Update permanently breaks / stops update progress at some point in a save chain

### ISSUE THREAD

**Issue by garryrot** [IHateMyKite/UnforgivingDevices#189]
When I use the mod for a longer time, i.e. saving and loading multiple times. At some point the mod will fail during the "update".

This permanently "bricks" unvorgiving devices in that chain of saves. So if I save the game and continue playing, unforgiving devices will never work, and I have to revert to an earlier game in which that never happened.

1. Start a game with unforgiving devices
2. Continue playing the game for some time, i.e. save and reload
3. At some point in time the "loading" starts to stop at some random "update progress"

**Actual Behavior**
1. Mod update will get stuck at random percentage
2. MCM does not work and will display update in progress (see screenshot)
3. I can equip and unequip devious devices without any message box or any scripted behavior

**Expected behavior**
1. Mod will finish update after each load and work as expected

**Additional Info**

I also do not get any warning / error that indicates that the loading of the plugin has failed. UD source code seems to indicate that a notification is displayed when UD fails loading, but that never happens.

**Possible Fixes / Workarounds**
The only fix I have found is reverting to the last working save

**Screenshots**
![ScreenShot542](https://github.com/IHateMyKite/UnforgivingDevices/assets/121590509/0f67a3c1-e8e7-4b91-9f56-0b680e23bbf3)

**Papyrus Logs**
[ud-fails-loading.log](https://github.com/IHateMyKite/UnforgivingDevices/files/14911097/ud-fails-loading.log)

**Skyrim Plugins / Load Order**
[skyrim-plugins.txt](https://github.com/IHateMyKite/UnforgivingDevices/files/14911118/skyrim-plugins.txt)
[skse-plugins.txt](https://github.com/IHateMyKite/UnforgivingDevices/files/14911120/skse-plugins.txt)

**Mod Versions**
- Unforgiving Devices 2.1.1
- Devious Devices NG 0.2.9
- Skyrim AE 1.6.640.0

**Comment by kurotatsu77** [comment]
I think your savegame just before this happens would be useful too.

**Comment by garryrot** [comment]
> I think your savegame just before this happens would be useful too.

Sure. Unfortunately I cannot really pinpoint how it happened, just that one worked and the one after already broke. So I included both. 

Last working save: https://www.mediafire.com/file/8r7novub8ri4f4v/last-working-save.7z/file 
First broken save: https://www.mediafire.com/file/b7w3buyrzcaum0a/first-broken.7z/file

When I restart the mod from that point, i do not manage to get the issue to re-occur.

**more info** I loaded the game multiple times from save 167, and continued to play. the issue only happened in the one save I attached.

**Comment by garryrot** [comment]
So I actually managed to re-produce the issue on "last-working-save.z7", i.e. save number 167.

It seems somehow random, maybe a race condition, but this save in particular is prone to it happening. I managed to make it happen twice, but most of the times it will work.

What I did:
1. Load Save 167
2. Wait 20-30 secs
3. With 20-30% chance, the update progress hangs at 16%, in all other cases UD loads as expected.

I made a save of this and uploaded it, so this save is the issue happening for the first time, based directly on "last-working-save.z7" (which still working):
https://www.mediafire.com/file/bni9eous7c8tpai/working-state-broke-for-the-first-time.7z/file

I also included papyrus and all SKSE plugin logs of it happening

**Comment by IHateMyKite** [comment]
Try to install this https://www.nexusmods.com/skyrimspecialedition/mods/96410. I have basically created this mod only to fix this issue, as this was issue happens in IWantWidgets if there are too many function calls. The NG version should fix this.

**Comment by garryrot** [comment]
> Try to install this https://www.nexusmods.com/skyrimspecialedition/mods/96410. I have basically created this mod only to fix this issue, as this was issue happens in IWantWidgets if there are too many function calls. The NG version should fix this. Might as well make the NG version required for UD3, as it is SE only anyway

Yeah it makes sense that its probably some issue with script overload.

I'll test it, thank you.

**Comment by garryrot** [comment]
So I installed IWantWidgets NG and haven't had this issue since. Though I didn't manage to get too many game hourse played yet

**Comment by IHateMyKite** [comment]
> So I installed IWantWidgets NG and haven't had this issue since. Though I didn't manage to get too many game hourse played yet

Was there any more issues with the mod ? If not, I will close this issue.

**Comment by garryrot** [comment]
> > So I installed IWantWidgets NG and haven't had this issue since. Though I didn't manage to get too many game hourse played yet
> 
> Was there any more issues with the mod ? If not, I will close this issue.

No there wasn't, I will close it for you thanks!
