### ISSUE TITLE
(Minor) DD 5.1 patch contains 5.2 records

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#19]
Description: Selecting 5.1+BRRF patch in FOMOD installs 5.2 DD patch that contains erroneous and unreferenced plugin records.
Seems like all 5.1 patches are based of 5.2
Verified issue for DD, BRRF, BRRF+For Him patches.

Version of skyrim: SE
Version of mod: 2.0b9
Used patches: per description.

**Comment by IHateMyKite** [comment]
Hopefully fixed
