### ISSUE TITLE
UDNative.dll+0136302 Crash on save load with commit 4740ef9 Nightly build

### ISSUE THREAD

**Issue by ThisIsPatrick** [IHateMyKite/UnforgivingDevices#203]
**Describe the bug**
Game crashes to desktop immediately after a save is done loading.

**Logs**
Crash log - https://paste.sh/13d306gD#2C3OSIk8Spdbjsj8voiNgRc8
UDNative log - https://paste.sh/lzs3eSsX#z2zKYXwxbEJRGUnGDw9njJjP
Papyrus log - https://paste.sh/GlGKhSOa#F7HMXFOea_EMxBZ6Jd0SuU79

**Extra details:**
Newly started game, 5-10 minutes in in an empty cell (Lakeview Manor.)
Nightly build of [commit 4740ef9](https://github.com/IHateMyKite/UnforgivingDevices/commit/4740ef97a2a6ecaa49d453940f33d58a0efb9ecb)
Devious Devices NG 0.37
Skyrim 1.5.97

Edit:
Based on the error in the UDNative log and the crash log, **DeviousDevicesAPI::g_API** appears to be null.
[UDNative.log error](https://github.com/IHateMyKite/UnforgivingDevicesNative/blob/2fdcd840537fe3c750dda33328081fecdebc83a9/src/UD_Diagnosis.cpp#L26)
[Crash log location](https://github.com/IHateMyKite/UnforgivingDevicesNative/blob/main/src/UD_PapyrusDelegate.cpp#L931)

Apparently, the reason is because the DD Api was updated and the Discord beta release is older than that,

If there's any extra information I can provide let me know.

**Comment by IHateMyKite** [comment]
You require latest compiled dll from https://github.com/ponzipyramid/DeviousDevicesNG. Its not public yet. You can download it from this PR (for testing) https://github.com/IHateMyKite/UnforgivingDevices/pull/201
