### ISSUE TITLE
DeviceMenu UI opened twice

### ISSUE THREAD

**Issue by AndbGame** [IHateMyKite/UnforgivingDevices#204]
**Describe the bug**
Unforgiving_Devices_3.0_NG_-_Experimental_19

**To Reproduce**
1. Open Device menu by action key
2. UI is doubled

**Screenshots**
https://github.com/user-attachments/assets/dbcbc0f2-2e27-4eba-aa99-5bd53e2b8893

**Additional context**
Looks keyup event fired twice
The problem is not permanent, and it depends a lot on how hard I press the key on my keyboard

Currently  I am trying next solution:
copy empty function `DeviceMenu()` to State `UpdatePaused`
```
Scriptname UD_CustomDevice_RenderScript extends ObjectReference  
...
State UpdatePaused
    ...
    Function DeviceMenu(bool[] aaControl); Disable DeviceMenu
    EndFunction
EndState
```
(I'm not sure exactly, but it seems to work)

**Comment by IHateMyKite** [comment]
Will try to find a way to fix this. Maybe I will just add some kind of cooldown when opening the menu. so it cant be opene more then once per second for example
