### ISSUE TITLE
"Could not load DD API!" UDNative.log error with latest NB of DDNG and UD

### ISSUE THREAD

**Issue by ThisIsPatrick** [IHateMyKite/UnforgivingDevices#205]
Unsure if this is an issue with UD or DDNG.

With the latest github nightly builds of both UD and DDNG, as well as testing self-compiled versions, UDNative.log gives an error that the DD API could not be loaded.
> [log] [error] [UD_GameEvents.cpp:67] Could not load DD API!

Another error shows up in the log shortly after:
> [log] [error] [UD_Diagnosis.cpp:26] Cant check database because it was impossible to import the functions!!!!!!!!!!!

I recompiled UD with some extra error logging, this is the exact line where LoadAPI returns false:
https://github.com/IHateMyKite/UnforgivingDevicesNative/blob/2fdcd840537fe3c750dda33328081fecdebc83a9/include/UD_DDAPI.h#L165

**Extra information:**
Skyrim 1.5.97
DDNG build https://github.com/ponzipyramid/DeviousDevicesNG/commit/15e4cc775a7bf2b6c3ec3b3ad3ee0eaf79e07b37
UD build https://github.com/IHateMyKite/UnforgivingDevices/commit/4740ef97a2a6ecaa49d453940f33d58a0efb9ecb
UDNative.log: https://paste.sh/2juABzdJ#isSrCcz6E5lg9swwjA2NDtoI
DeviousDevicesNG.log https://paste.sh/K0LZD1J9#VZ_J1XYymz2ibAYw5449AfO7
skse64.log https://paste.sh/Bz6UB5jp#WFbBG8sbJKgGManfn6PiWjqB

**Comment by IHateMyKite** [comment]
Thats because it looks like the DDNG NB is broken. Mainly, it build debug version, which barely works for other peaple then the person who made it. And in this case, this is made by GitHub action, so it will not work correctly for anyone. Try this locally build version. Used the latest commit 15e4cc7
[DeviousDevices.zip](https://github.com/user-attachments/files/16828580/DeviousDevices.zip)

**Comment by Gamerooni** [comment]
I think the reason none of us could replicate your issue is that you were on 1.5.97.

Even so, that can't be the cause of your error. UD and DDNG use CommonLibNG, which should work regardless of your version.

**Comment by IHateMyKite** [comment]
I think that issue might be acutally in SKSE. As the SKSE for 1.5.97 might be using different event handlingthen the one on last version. And DDNG is using the SKSE events for sending the API so that would make sense. I will give a look at the SKSE on github to see if there were any changes that can do this

**Comment by IHateMyKite** [comment]
Also, looking now at the skse64.log you shared, for some reason the required event is not called for DDNG. It is correctly dispatched by UD, but not received by DDNG. And strangely, that event is also received by racemenu.

**Comment by IHateMyKite** [comment]
> skse64.log with RaceMenu disabled https://paste.sh/1hQasc26#DUJeWOgP9k0yDec3ODJxohrj `[log] [error] [Interfaces.cpp:272] Failed to dispatch message to all listeners` `[log] [error] [UD_GameEvents.cpp:66] Could not load DD API!`
> 
> Same results until... https://paste.sh/M3NbnuJf#skh0zFFm1YsifdCiNFR2J-Jh
> 
> Enabling any SKSE plugins past this breaks it again.
> 
> Edit: Replacing mfgfix with another dll also "works." https://paste.sh/pE4gDFe5#KkFD-Ko5vwaPofo5be0JOkvn

I have been looking at the skse sources for some time now, and I can tell this is 100% skse issues. It just doesnt work. I will just rework it to use extern again, as I dont feel like deeling with this bs

**Comment by IHateMyKite** [comment]
Try this, I reworked API to use good old extern, so I dont have to deal with skse.
[API Rework.zip](https://github.com/user-attachments/files/16976726/API.Rework.zip)

**Comment by IHateMyKite** [comment]
That is essentially the same thing I implemented yesterday. Only difference is that I use LoadLibrary, instead of GetModuleHandle. Will probably just keep it that way, as its working, and it was also working this way before when UD was getting DD api using the extern functions
