### ISSUE TITLE
(Trivial) Invalid keyword papyrus error

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#21]
Description: potential issue with Minigame Disabler, papyrus is cursing on misisng keywords. Not sure what causes this, but happens frequently, on actor orgasm.

![изображение](https://user-images.githubusercontent.com/30041703/164059075-d1d83cf6-1843-4003-926f-1acb05fb5d18.png)

Version of skyrim: SE
Version of mod: 2.0b9 commit https://github.com/IHateMyKite/UnforgivingDevices/commit/84d5fb1d26527d575db04faa64fc5b2df887538c
Used patches: DD 5.1+BRRF, DCL, LBS

**Comment by IHateMyKite** [comment]
To be fair, I have no idea what happened here. Did this pop up after minigame ended or was it showing the error all the time?

**Comment by BreadDain** [comment]
It showed this error only on orgasm, which supposedly stopped the minigame. I was invistigating MAO and stumbled upon it, didn't pay too much attention since it didn't break anything.

**Comment by IHateMyKite** [comment]
I don't see any way in fixing it. Closing.
