### ISSUE TITLE
(Trivial) Base details tooltip is incorrect for helper

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#24]
Description: observing someone's devices from helper perspective gives incorrect tooltip for lock accessibility, usually shows Unreachable when expected at least "Easy to reach". With that said, actual result is that locks can be easily reached on practice, so it's just a tooltip bug.

Version of skyrim: SE
Version of mod: 2.0b9 commit https://github.com/IHateMyKite/UnforgivingDevices/commit/84d5fb1d26527d575db04faa64fc5b2df887538c
Used patches: DD+BRRF, DCL, LBS

**Comment by IHateMyKite** [comment]
The accessibility value is changed when a minigame with helper starts. In some cases, it increases accessibility. Also, the accessibility shown in details menu is always the basic one, before all other modifiers are applied. So it if never show different value if you are looking at the device from different perspective.

**Comment by BreadDain** [comment]
It would be very strange, wearer had only restrictive boots equipped and I was inspecting their accessibiltiy values, it showed Impossible to reach, but on practice it was simple. Even if player was wearing them they should probably have an easy access.

Might be tied to a different issue, for example items appear to be unequipped. But that's vanilla behaviour on NPCs

**Comment by IHateMyKite** [comment]
Will give it a look
