### ISSUE TITLE
(QoL) Shields

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#25]
Shields have to go during minigame animations, they are clipping a lot. Unequipping them would be an unpleasant user experience, so I think something like device hider should be applied to them during animations, so they stay equipped but hidden.

There are plenty of similar mods that doing that job for quivers, hiding them if bow unequipped, but those that don't just unequip them are written in .dlls without source files. DD framework has device hider functionality, but it seems it is also tied to .dll, although can be used via interface.

**Comment by IHateMyKite** [comment]
Don't know how to do it. I think that a better idea will be to just unequip the shield and then reequip it.

**Comment by BreadDain** [comment]
Torches can be also added on par to that, which are technically shields.
