### ISSUE TITLE
(Minor) NPC with 0 stamina as helper

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#26]
Description: if player attempts to start struggle minigame with NPC helper that has 0 stamina (in my case Serana, vampire, stamina doesn't regenerate outside during daytime) the minigame will begin for the duration of a single tick and immediately cancel itself, inflicting debuff.

Expected behaviour: mod prevents minigame start, telling that helper is too exhausted for that.

Note: was trying to get rid of a device both with "Desperate" and "With help of Magic" ways, same issue occurs with both.

Version of skyrim: SE
Version of mod: 2.0b9 commit https://github.com/IHateMyKite/UnforgivingDevices/commit/e60aa0db9c3aa307a8c8ea3df8a78840f41dcba0
Used patches: DD+BRRF, DCL, LBS

**Comment by IHateMyKite** [comment]
Issue is this part of [code](https://github.com/IHateMyKite/UnforgivingDevices/blob/e60aa0db9c3aa307a8c8ea3df8a78840f41dcba0/Scripts/Source/UD_CustomDevice_RenderScript.psc#L3106-L3114). This only checks wearer, not helper. But there is already [CheckMinAVHelper ](https://github.com/IHateMyKite/UnforgivingDevices/blob/e60aa0db9c3aa307a8c8ea3df8a78840f41dcba0/Scripts/Source/UD_CustomDevice_RenderScript.psc#L3791)function, so i guess I only forget to add it. If you want, you can just copy the previous block and just replace the CheckMinAV function and it should work as intended.
