### ISSUE TITLE
(Minor) Save/Load Settings functionality doesn't affect some of mcm menu entries

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#3]
Affected settings in Custom devices menu page: Update time, Widget Pos X, Widget Pos Y, Patch mult, Swimming difficulty

Steps to reproduce:
- Start a new game
- Change listed settings in Custom devices page to something else
- Save settings
- Exit to main menu, start a new game
- Load settings

Version of skyrim: SE
Version of mod: 2.0b8
Used patches: DD+BRRF, DCL, LBS

**Comment by IHateMyKite** [comment]
**FIxed**
