### ISSUE TITLE
(Trivial) onUpdate event in exhaustion effect

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#30]
Description: Papyrus throws an error when trying to execute [OnUpdate call linked to exhaustion effect.](https://github.com/IHateMyKite/UnforgivingDevices/blob/40e8efb1f1a7bf77ee066ef8e535a865ce9fef53/Scripts/Source/UD_CustomDeviceExhaustion_MagEffect.psc#L21-L26) Happens on orgasm and on game load, but seemengly without any issues. I guess controls are getting locked properly during onEffectStart and are removed onEffectFinish but are never updated if something else modifies them in a mean time. Possible the other effect that ends during the other will unlock the possibility to wait.
Edit: it doesn't happen all the time but only sometimes, I've already previously reported this issue. Not 

Expected: controls are being re-locked during onUpdate event -or- onEffectFinish sends an event to other effects to re-lock controls immediately if they are still present on that character.
![изображение](https://user-images.githubusercontent.com/30041703/165553893-04bd9a69-de0b-48b0-a2e6-3e36325da354.png)

Version of skyrim: SE
Version of mod: 2.0b9 [40e8efb](https://github.com/IHateMyKite/UnforgivingDevices/commit/40e8efb1f1a7bf77ee066ef8e535a865ce9fef53)
Used patches: DD+BRRF, DCL, LBS

**Comment by IHateMyKite** [comment]
This is know issue. Sadly I still don't know how to fix it. On the other hand, this issue is in mod for long time and I don't think it is causing any issues.

**Comment by IHateMyKite** [comment]
Closing this as I don't think its longer relevant.
