### ISSUE TITLE
(Major) xEdit patch script no longer works as intended, BRRF patch is broken.

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#35]
Description: Most devices are no longer affected by UD device patch, mod doesn't recognize them as interactable. In fact, only these inventory devices are present and they don't have script patch-ups:
![изображение](https://user-images.githubusercontent.com/30041703/166116916-b66d1ecb-f9c1-4c40-b6fb-4a85161e37e8.png)

Deeper investigation - trying to process devices with xEdit script no longer produces intended results, it doesn't edit inventory devices in any way unless is used only on single record at a time, fails to do it en masse.
[00:00] Exception in unit UD_Libs line 245: [Exception] Load order FileID [0D] can not be mapped to file FileID for file "Devious Devices - Expansion.esm"

It also tries to modify DD Expansion rendered device record with a pointer to nonexisting record (DD 5.2?)
![изображение](https://user-images.githubusercontent.com/30041703/166118135-0f9e5a6c-d296-42e4-9457-e2d9fa6bada9.png)

Only 5.1 BRRF patch is affected it seems, tested on basic and BRRF+For Him, both of them worked. How peculiar. Maybe script is not intended for patching DDi and DDx and I just misused it, but the problem with patch is present.

Version of skyrim: SE
Version of mod: 2.0b10
Used patches: DD5.1+BRRF, DCL, LBS
Patching script: 1.6
xEdit version: 4.1.4 experimental

**Comment by IHateMyKite** [comment]
Do I understand right that you are trying to use xEdit patching script? And if so, what mod are you trying to patch?

**Comment by BreadDain** [comment]
It is a complex problem
a) DD 5.1 BRRF UD patch is entirely broken
b) I was trying to apply script on DDi and DDx armors to repair it

**Comment by IHateMyKite** [comment]
a) Now I understand what you mean. I think I forget to apply the patch and then autocleaned it, so it cleaned everything except for renderDevices. 
b) You also have to patch the DDa. It is also important that you copy the records in the right order (so they are overwritten right). DDa -> DDi -> DDx -> BRRF -> For Him. Then start patch and it should work. You also have to copy it "with overwriting", else it will not work.
