### ISSUE TITLE
(Minor) Issues with "Chaotic" plugs

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#39]
Description: Filled soulgem and Black soulgem plugs have problems regarding repeated activations and vibration status information. Both pair types cannot be activated after certain amount of activations (second activation? or only after long period of vibrating?), cannot start vibrating by Sentient activation nor by belt activations. Activation message appears, no vibration occurs, log doesn't show anything related to vibration except calling vibrations on devices sometimes/

Filled plugs vibration status shows that plugs are always off. Black soulgem - paused, which doesn't change during activation.

Expected: plugs vibrate normally when activation is called, getting unpaused if is Black soulgem.
Actual: both plugs become permanently silent, activations don't do anything.

Note: both plugs have unique interactions, one is always Edging, another is Chaotic (switches power randomly)

Version of skyrim: SE
Version of mod: 2.0b10
Used patches: DD5.1, DCL, LBS

**Comment by BreadDain** [comment]
![изображение](https://user-images.githubusercontent.com/30041703/166303356-505df912-497b-4171-bf07-99b8216a9e6a.png)

![изображение](https://user-images.githubusercontent.com/30041703/166303747-457b36f7-fc59-42de-99ee-18051c68728c.png)

**Comment by IHateMyKite** [comment]
Probably found the source of the issue. Basically, [this ](https://github.com/IHateMyKite/UnforgivingDevices/blob/e3f6e933b3ed9679d552b294314d65174cb39cc8/Scripts/Source/UD_CustomVibratorBase_RenderScript.psc#L426)line of code should have [here](https://github.com/IHateMyKite/UnforgivingDevices/blob/e3f6e933b3ed9679d552b294314d65174cb39cc8/Scripts/Source/UD_CustomVibratorBase_RenderScript.psc#L428), on the bottom of function, not in an if statement. Will require you to test it once it is merged.

**Comment by IHateMyKite** [comment]
Fixed with [Rework Oragsm/Arousal check](https://github.com/IHateMyKite/UnforgivingDevices/commit/58bd259ee655d982df373e0cc1693d802df38a36)
