### ISSUE TITLE
(Minor) Loading mcm menu setting with autocrit checkbox enabled leaves auto crit chance slider setting disabled

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#4]
![изображение](https://user-images.githubusercontent.com/30041703/162228645-ba25857c-14e9-41fb-9b50-cf6e975f5897.png)

Steps to reproduce:
- Start a new game
- Load pre-existing settings with autocrit function enabled

Version of skyrim: SE
Version of mod: 2.0b8
Used patches: DD+BRRF, DCL, LBS

**Comment by IHateMyKite** [comment]
**FIxed**
