### ISSUE TITLE
(Minor) Hardcore control restriction breaks dialogue

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#45]
Description: If during some sort of dialogue player is getting equipped with a restrictive device with an intention of proceeding with dialogue after, UD Hardcore mode will force exit from that dialogue, potentially breaking some quests.

Needs verification if it is not a specific mod setup.

Version of skyrim: SE
Version of mod: 2.0b10
Used patches: DD 5.1, DCL, LBS

**Comment by IHateMyKite** [comment]
Looks like there will need to be some check so effect is applied only after dialogue ends. Will give it a look.

**Comment by IHateMyKite** [comment]
Fixed with e0becd3
