### ISSUE TITLE
(Minor) Device damage on hit

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#48]
Description: certain creatures don't deal damage to device health/condition. Werewolves were already reported and fixed, but there are other creatures like mudcrabs for example. Possibly there other sources of damage that are getting ignored such as drain life, hazard and explosions such as placed runic traps, dots like burning and etc.

Version of skyrim: SE
Version of mod: 2.0b10
Used patches: DD 5.1, DCL, LBS

**Comment by IHateMyKite** [comment]
Tested it. Looks like thees kind of weapons are actually correctly processed by devices, but their base damage is 0. For now, I just made it so if weapon base damage is 0, 5 will be used instead.

**Comment by IHateMyKite** [comment]
Fixed with db16f18
