### ISSUE TITLE
(Minor) Hobble dress and leg cuffs tie up

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#51]
Description: Relaxed version of hobble dress overrides leg cuffs tie up effect, restoring speed and animation back to normal.

Version of skyrim: SE
Version of mod: 2.0b10
Used patches: DD 5.1, DCL, LBS

**Comment by IHateMyKite** [comment]
Will give it a look, but it is possible that this issue is unfixable.

**Comment by IHateMyKite** [comment]
Take some time but finally give it a look. The issue is most likely unfixable. I only added more checks so the animation and speed is restored correctly, but having relaxed hobble equipped over leg cuffs will still remove the effect.
