### ISSUE TITLE
(Compatibility) Recipe conflict with CACO

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#56]
Description: crafting recipes that require salt are conflicting with [Complete Alchemy and Cooking Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/19924) internal recipe mechanics, the mod splits salt piles into smaller items with different id which makes UD recipes unable to be fullfilled. Requires additional patch to be solved.

Version of skyrim: SE
Version of mod: 2.0b11 [72eaa74](https://github.com/IHateMyKite/UnforgivingDevices/commit/72eaa746ea174fb8c34296348770aecfcced5e8e)

**Comment by IHateMyKite** [comment]
Will give it a CACO try and try to create patch. It should not be that hard, but first I will need to understand how the mod works.

**Comment by BreadDain** [comment]
I think it just runs a script on player inventory when entering a cooking station, replacing all ingredients with mod's counterpart. The most simple approach would be redirecting UD to use mod's ingredient, but that would require either an additional plugin slot, which is unfavourable for most people, or maintain a different version for main UD plugin, keeping the patch there.
Another solution is not to use vanilla cooking activator to stop triggering CACO behaviour. Not sure if it'll work though.

**Comment by Ethryan** [comment]
[Unforgiving Devices - CACO Patch.zip](https://github.com/IHateMyKite/UnforgivingDevices/files/11159568/Unforgiving.Devices.-.CACO.Patch.zip)
Changed the 3 recipes i could find that had salt in them, and made it into a CACO Patch.
