### ISSUE TITLE
(Minor) Plugin contains 3 errors

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#63]
Description: validating plugin for errors throws 3 of them. Probably has some symptoms in game.

![изображение](https://user-images.githubusercontent.com/30041703/176944480-e58c38dd-e61f-4a9a-b14b-5985d08519cc.png)
![изображение](https://user-images.githubusercontent.com/30041703/176944542-231116a9-04f5-40f9-91d6-0b4e53339257.png)

Version of skyrim: SE
Version of mod: 2.0b13

**Comment by IHateMyKite** [comment]
For some reason, this is only issue in SE. In LE, it just uses NULL reference, and it doesn't look like it's causing any issue.

**Comment by BreadDain** [comment]
Suspect it might be form 43/44 differences in nutshell. As far as I know form 44 works quite well on LE, but can't be 100% sure, can only tell that personally saw esl flagged .esps working on LE, which are definitely form 44.

**Comment by BreadDain** [comment]
Issue is might be an xEdit specific-bug and won't cause any actual issues in game. Seen other mods with similar symptoms. Closing.
