### ISSUE TITLE
(Minor) Device patching doesn't refill device stats

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#69]
Description: additional locks or health that were gained during "repatch" procedure are not getting properly locked/restored

Version of skyrim: SE
Version of mod: 2.0b13
Used patches: DD5.1+BRRF, DCL, LBS

**Comment by IHateMyKite** [comment]
Didn't implement this yet. Will give it a look.

**Comment by IHateMyKite** [comment]
Implemented in 1cbf3fe and tested. Closing.
