### ISSUE TITLE
Maximum amount of locks is incorrect

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#71]
Description: Max. Locks patcher setting, which presumalbe limits maximum amount of locks the device can possibly get, is either ignored, incorrect, or is unexpectedly increased by 1 in the result. Device in subject was Steel Chastity Belt (Padded), limit is set to 5, got 6 locks in return.
Repatching the device further increased the amount of locks by 1 to 7 in total.

Version of skyrim: SE
Version of mod: 2.0b13
Used patches: DD5.1+BRRF, DCL, LBS

**Comment by IHateMyKite** [comment]
Closing this as its invalid.
