### ISSUE TITLE
Helping mechanic cooldown conditions

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#72]
Description: Cooldown on "Help" functionality locks all device interaction, expected that it affects struggle only. Helper is not able to inflate plugs, unlock with key, charge a plug, i.e. anything that doesn't involve exhaustion or struggle.

Version of skyrim: SE
Version of mod: 2.0b13
Used patches: DD5.1+BRRF, DCL, LBS

**Comment by IHateMyKite** [comment]
Moved the cooldown function in to same block which apply exhaustion, so from now on the cooldown will activate only if minigame apply exhaustion to player.

**Comment by IHateMyKite** [comment]
Should be long fixed, closing.
