### ISSUE TITLE
Helper orgasm interaction

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#73]
Description: If helper orgasms during struggle minigame this won't cancel the animation/minigame, and orgasm animation wouldn't play. Expected that minigame is stopped and helper plays proper animation.

Version of skyrim: SE
Version of mod: 2.0b13
Used patches: DD5.1+BRRF, DCL, LBS

**Comment by IHateMyKite** [comment]
Can this be replicated?

**Comment by BreadDain** [comment]
It cannot, closing.
