### ISSUE TITLE
NPC can't remove their own plugs

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#74]
Description: NPCs are incapable of removing their own plug (ifnlatable anal in my case). Minigame starts, animation is played, stamina is being drained, but no damage is dealt to the plug.

Version of skyrim: SE
Version of mod: 2.0b13
Used patches: DD5.1+BRRF, DCL, LBS

**Comment by IHateMyKite** [comment]
Found the issue. In general. the there is no functionality to simulate key press from npc, so I will have to add one

**Comment by IHateMyKite** [comment]
Implemented but didn't test it. Will test it and close if it works.

**Comment by BreadDain** [comment]
It seems that damage is quite low, plugs are really easy to remove by player. NPCs simulate regular device struggle instead it seems, dealing less damage.

**Comment by IHateMyKite** [comment]
Reworked it in f595566. Till now, it was only simulating one press per second, which is very low. So I have reworked it to simulate 4 presses. Now it should be easier for NPC to remove plug. Closing for now.
