### ISSUE TITLE
Helper cooldown after plug removal

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#75]
Description: Helping to remove a plug (infl anal) with a minigame doesn't set helper on cooldown from helping with devices, expected - inflicts cooldown and exhaustion if it involves a minigame.

Version of skyrim: SE
Version of mod: 2.0b13
Used patches: DD5.1+BRRF, DCL, LBS

**Comment by IHateMyKite** [comment]
Found the issue. Should be fixed in next push.
