### ISSUE TITLE
Helper cooldown after helping to unlock device with a key

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#76]
Description: Helping to Unlock a device with key sets helper on cooldown for any further help, expected: ?, not exhaustive action so ideally shouldn't inflict a cooldown?

Version of skyrim: SE
Version of mod: 2.0b13
Used patches: DD5.1+BRRF, DCL, LBS

**Comment by IHateMyKite** [comment]
Fixed with  #72. See details there. Closing
