### ISSUE TITLE
Helping NPCs who are locked within orgasm animation

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#77]
Description: It is possible to start helping an NPC to struggle from any device while they are orgasming, expected: mod prevents help and tells that actor is busy.

Version of skyrim: SE
Version of mod: 2.0b13
Used patches: DD5.1+BRRF, DCL, LBS

**Comment by IHateMyKite** [comment]
Will implement. Should be no problem.

**Comment by IHateMyKite** [comment]
Should be implemented. Closing
