### ISSUE TITLE
Conc. Black goo poison interaction

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#78]
Verification is required
Description: Poisoning with conc. black goo makes NPCs yell "Keep your goddamn spells to yourself!" at the end of wrapping them in bondage. Doesn't affect anything, just ridiculous.

Version of skyrim: SE
Version of mod: 2.0b13
Used patches: DD5.1+BRRF, DCL, LBS

**Comment by IHateMyKite** [comment]
Should be fixed. Closing.
