### ISSUE TITLE
Balancing of cuff tie up mechanic

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#79]
Struggling or helping to struggle from tied up cuffs is immensely hard, harder than even ebonite elbowbinders or some rare abadon restraints. Ideally it supposed to be not harder than cutting/struggling from rope cuffs.

**Comment by IHateMyKite** [comment]
For now I rebalanced it by increasing untie amount 3x per second. Also increased crti amount and reduced crit failure penalty. Hopefully it will now not be too easy.

**Comment by IHateMyKite** [comment]
Please test if its now better.

**Comment by BreadDain** [comment]
Works well enough. Closing
