### ISSUE TITLE
NPC plug deflation

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#80]
Description: Helping NPC to deflate a plug at inflation level 1 has no effect on it. On contrary, commanding them to do so does deflate it properly. Plug in question was Weak Abadon inflatable anal plug.

Version of skyrim: SE
Version of mod: 2.0b13
Used patches: DD5.1+BRRF, DCL, LBS

**Comment by IHateMyKite** [comment]
I think I found the cause of problem. Will test the solution and push the fix.
