### ISSUE TITLE
NPC device lock information

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#81]
Description: NPC device information doesn't properly show how many locks are jammed, only stating that there are jammed locks.
![изображение](https://user-images.githubusercontent.com/30041703/178509169-4d646759-7b34-4695-9589-0dbe54c43c04.png)

Version of skyrim: SE
Version of mod: 2.0b13
Used patches: DD5.1+BRRF, DCL, LBS

**Comment by IHateMyKite** [comment]
Try latest to use latest indev version. I have reworked how jammed locks work, so it should now work correctly

**Comment by BreadDain** [comment]
Resolved
