### ISSUE TITLE
Impossible to repair NPCs locks

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#82]
Description: There is no possibility to help or command NPCs to repair their jammed locks.
Edit: the issue is inconsistent, sometimes it is possible and sometimes not.

Version of skyrim: SE
Version of mod: 2.0b13
Used patches: DD5.1+BRRF, DCL, LBS

**Comment by IHateMyKite** [comment]
This was most likely issue with device menu. I have found bug that if you open device menu from inventory, command option will be not avaible. Will be fixed in next push
