### ISSUE TITLE
Use of Game.GetPlayer() method

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#84]
Description: code containts excessive use of GetPlayer() method, [#1](https://github.com/IHateMyKite/UnforgivingDevices/blob/b5ce9abb43a4edbf152ca50f2d4f0285328b8f30/Scripts/Source/UD_OrgasmManager.psc#L652-L676) [#2](https://github.com/IHateMyKite/UnforgivingDevices/blob/b5ce9abb43a4edbf152ca50f2d4f0285328b8f30/Scripts/Source/UDCustomDeviceMain.psc#L1247-L1268) +144 search matches according to a project search. According to [this thread](https://www.reddit.com/r/skyrimmods/comments/gm5zbq/papyrus_best_practicestechniques/) this function is overly slow and is better to be replaced with a property.

**Comment by IHateMyKite** [comment]
Nice idea. Implemented with 34493bc. Closing
