### ISSUE TITLE
Alchemical ingredients balance (beta 14)

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#85]
Description: Black goo AlchFortifyEnchanting is way to powerful for vanilla-like balance, both CACO and base game have the most powerful and rare ingredients capped at 1.7xx modifier magnitude while Black goo has it at 5 and is a very common ingredient.

Concentrated black goo has the same modifier set at 0, bug.

If the original idea was providing powerful enchanting boost but restraining the imbiber - this can be bypassed by combining Black goo with vanilla ingredients, has to be a new magic effect with a different name for that so only black goos combined can make enchanting boost effect appear in final potion.

Alchemical ingredients that further boost alchemy do not exist in base game and Dragon nuts breaks this rule, and also cannot be combined with anything. The power modifier of that enchantment is way too high as well.

Most powerful AlchDamageHealth modifier in CACO comes from rare Chokeberries at 13.9 magnitude value. Dragon nuts have them at 40, this can kill anyone in 1 hit.

Correct alchemical stamina fortification effect is AlchFortifyStamina "Stamina Fortification" [MGEF:0003EAF9], modifier range is around 5.0-8.0. Dragon nuts are using wrong food-related modifier instead.

Fortify Barter effect found on Cooked Dragon Nuts is incompatible with CACO, the latter uses Fortify Speech effect instead, note for a future compatibility patch. 
Otherwise the Fortify Barter effect magnitude is 5 times higher than any regular vanilla ingredient has.

Version of skyrim: SE
Version of mod: 2.0b13 [dca6987](https://github.com/IHateMyKite/UnforgivingDevices/commit/dca698775ff7696cc5d77d03297b7178f0f541dd)
Used patches: DD5.1+BRRF, DCL, LBS

**Comment by IHateMyKite** [comment]
Thanks for feedback. Will rebalance the ingredients. Also, I will replace the Fortify Barter with Regenerate Health. Still dunno if it will be compatible with CACO.

**Comment by BreadDain** [comment]
Yes it will, CACO tries to preserve vanilla effects as much as it can, some of exceptions are mostly vanilla bugfixes.

**Comment by IHateMyKite** [comment]
Fixed with f595566. Closing

**Comment by BreadDain** [comment]
Reopening so there is no need to create another issue. Applicable for beta 14

Dragon Nuts AlchDamageHealth "Damage Health" [MGEF:0003EB42] have a duration of 0, expected 1
Purified Goo AlchDamageHealth "Damage Health" [MGEF:0003EB42]  has a duration of 0, expected 1
Purified Goo AlchCureDisease "Cure Disease" [MGEF:000AE722] has magnitude of 0, expected 1

**Comment by IHateMyKite** [comment]
Are there other changes in provided esp, then the ones you mentioned?

**Comment by BreadDain** [comment]
I was referencing release version plugin, there might be unsaved changes. To be safe: in xEdit compare with my plugin and merge changes to Ingredient records:
![изображение](https://user-images.githubusercontent.com/30041703/181749928-a2b0e8d8-7a52-4efd-adc2-8be6773f91f6.png)

![изображение](https://user-images.githubusercontent.com/30041703/181749911-1e3c5de7-506c-4fee-bd90-3a68e18a6e1c.png)

**Comment by IHateMyKite** [comment]
Check last indev version of esp. I think that all should be implemented.

**Comment by BreadDain** [comment]
Latest indev: dragon nuts and purified goo Damage Health effect have area of 1 instead of duration, the latter is still at 0

**Comment by IHateMyKite** [comment]
Everything should now be OK. Closing this (hopefully for good).
