### ISSUE TITLE
Struggling (from gag) while wearing a yoke plays armbinder animation.

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#88]
Struggling (from gag) while wearing a yoke plays armbinder animation.

_Originally posted by @BreadDain in https://github.com/IHateMyKite/UnforgivingDevices/discussions/31#discussioncomment-3278407_

Description: Elbowbinder/Elbow hook break yokes/elbow hook animations. Results in mismatched animations for latter type of devices, being restrained in a yoke will play elbowbinder animations. General fixes or zadquest reset do not solve the issue.

Steps to reproduce after new game UD+DD initialization:
Equip gag
Equip elbowbinder
Struggle from gag to try animations
Strip elbowbinder, equip elbow hook, check animations again.
Strip hook, equip yoke, check animations.

Version of skyrim: SE
Version of mod: 2.0b14
Used patches: DD5.1+BRRF, DCL, LBS

**Comment by IHateMyKite** [comment]
Should be already fixed with 7b41bb1. Basically I added new property which stores HB device so it can be quickly accessed. Problem was that I forget that once the HB is unlocked, it will not get removed from property, still forcing the unlocked device. You can try latest indev version if it will solve the issue.

**Comment by BreadDain** [comment]
> Should be already fixed with [7b41bb1](https://github.com/IHateMyKite/UnforgivingDevices/commit/7b41bb1372e8c0fa054931cb2cd0e10d2f164d86). Basically I added new property which stores HB device so it can be quickly accessed. Problem was that I forget that once the HB is unlocked, it will not get removed from property, still forcing the unlocked device. You can try latest indev version if it will solve the issue.

This commit has a blocker issue:
![изображение](https://user-images.githubusercontent.com/30041703/182905468-e2e4d89a-7577-4845-89d7-bfe582559a24.png)

Not possible to test it further

**Comment by BreadDain** [comment]
> Should be already fixed with [7b41bb1](https://github.com/IHateMyKite/UnforgivingDevices/commit/7b41bb1372e8c0fa054931cb2cd0e10d2f164d86). Basically I added new property which stores HB device so it can be quickly accessed. Problem was that I forget that once the HB is unlocked, it will not get removed from property, still forcing the unlocked device. You can try latest indev version if it will solve the issue.

Commit [7b41bb1](https://github.com/IHateMyKite/UnforgivingDevices/commit/7b41bb1372e8c0fa054931cb2cd0e10d2f164d86) and [d94b446](https://github.com/IHateMyKite/UnforgivingDevices/commit/d94b4460db4694f524939380a9e3ac49d0cecdbf) has a blocker issue:
![изображение](https://user-images.githubusercontent.com/30041703/182906430-38d11cc5-c445-48c1-8047-cb6fa4142c97.png)

Can't proceed further with testing. Something I've messed up myself maybe? Can't see that method in

**Comment by IHateMyKite** [comment]
This is because I have added compatibility for DD beta 7 expressions. To compile the code you will now need beta 7 sources. Mainly, at least the expression ones and updated zadlibs.

**Comment by BreadDain** [comment]
Installed and linked compiler to [beta 7 scripts](https://www.loverslab.com/topic/69936-devious-devices-framework-developmentbeta/?do=findComment&comment=3823566) and [your expression modification](https://www.loverslab.com/topic/69936-devious-devices-framework-developmentbeta/?do=findComment&comment=3826964) - still a compilation failure. 
Honestly, I have no idea how this will even run on non-DD-beta clients if methods are missing from declaration.

**Comment by IHateMyKite** [comment]
These "missing" methods are extended from beta 7 **zadlibs** file
![snap](https://user-images.githubusercontent.com/103142567/183301777-82bcc92f-9162-491d-955a-884442da14af.jpg)

Check that you have right **zadlibs** file. Don't forget to check that all scripts are in SE script directory, not the LE one.

**Comment by BreadDain** [comment]
Sorry, my bad, apparently compiler picks up first source file from the provided list of sources, means that putting beta 7 at the bottom would just ignore its files if 5.1 sources are also linked at the beginning of the list. In other words priority increases from bottom to top.

On "missing methods" I've actually meant that 5.2 beta 7 zadlibs will not be present for 5.1 users, so I think that if UD calls ApplyExpression_v2 it will fail to do anything. Or maybe I am just wrong about it/Papyrus will solve it by itself.

Will try to check animations issue when I can.

**Comment by BreadDain** [comment]
Cannot reproduce it anymore with the same steps.

**Comment by IHateMyKite** [comment]
Alright, thanks for testing. Closing this.
