### ISSUE TITLE
(Minor) Inconsistent lockpicking results

### ISSUE THREAD

**Issue by BreadDain** [IHateMyKite/UnforgivingDevices#9]
Description: lockpicking actual results don't suit outcomes chosen by the mod. Issue is easily reproduced if minigame is interrupted by NPC line of sight. There is a noted specific that mod tries to pick previous lockpicking result instead of current one, issue is (almost?) impossible to reproduce during uninterrupted minigame.
![изображение](https://user-images.githubusercontent.com/30041703/162639097-5688493a-7377-4aab-bc5d-10f1b7f52cf8.png)

Preconditions:
1. Go to crowded place where you are constantly being observed
2. Equip any device with plenty of locks on it, I've used Steel Padded leg cuffs with 7-8 locks
3. Have suffice stamina to sustain lengthy struggle, 200 is enough

Steps to reproduce:
1. Play minigame with different outcomes, try to purposely break lockpicks to fail minigames but continue struggling

Note: I've tried to re-enforce conditions to be explicitly strict, it didn't resolve the issue. This can help to assume that conditions are not at fault and issue happens in-between function call where unexpected minigame interruption is being at fault.
if !_LockPickContainer.IsLocked()
		LockpickMinigameResult = 1 ;player succesfully finished minigame
	elseif remainingLockpicks == usedLockpicks && remainingLockpicks <= UD_LockpicksPerMinigame
		LockpickMinigameResult = 0 ;player exited minigame before trying to pick the lock
	elseif remainingLockpicks > 0 && remainingLockpicks <= UD_LockpicksPerMinigame
		LockpickMinigameResult = 2 ;player aborted mnigame after breaking at least one lockpick
	else
		Log("[UD]: all conditions failed, happened due to script overlapping.",1)
	endif

**Comment by IHateMyKite** [comment]
I will try to fix it by finally adding a way to prevent player from being detected while lockpicking. I have found this [post ](https://www.reddit.com/r/skyrimmods/comments/dhg7qq/invisibility_without_being_invisible/)which explain how it is done. I never added perk so it may still take some time to implement.

**Comment by BreadDain** [comment]
![изображение](https://user-images.githubusercontent.com/30041703/163482443-e47ff36f-b0c1-4ff1-99e3-c5c3ffc37c2f.png)
Issue persists on latest commit, requesting reopening.

**Comment by IHateMyKite** [comment]
Found the issue and fixed it. Will commit short time and then release next beta.
