### ISSUE TITLE
(QoL) Fix gramar/typos, part 1

### ISSUE THREAD

**Issue by IHateMyKite** [IHateMyKite/UnforgivingDevices#93]
[LL link ](https://www.loverslab.com/topic/165197-unforgiving-devices/?do=findComment&comment=3873775)

**Comment by BreadDain** [comment]
Are translation files still planned for scripts? Plugin typos/bad wording can be fixed with [xTranslator](https://www.nexusmods.com/skyrimspecialedition/mods/134) easily, but I am afraid to touch any writing since it is not my native language as well.

**Comment by IHateMyKite** [comment]
I gave up on translation files as it seems it only correctly works for MCM. Using the file for message box or notification will not work correctly. There are many strings UD which are combination of more string/values, and it seems like that is not currently a supported feature outside of MCM. It looks like the only way to do that is using the xTranslator as you mentioned.
