### ISSUE TITLE
Player controls block

### ISSUE THREAD

**Issue by kurotatsu77** [IHateMyKite/UnforgivingDevices#97]
In the current build found fun bug - when registered NPC orgasms, player UD controls stop working.
How to reproduce : get any follower, register them and equip with plenty of arousing devices to make her cum a lot.
When she orgasms observe . button not working and not calling devices menu, if you struggle during this event - A, S, D and even E button will not work.
As soon as her animation stops - controls restored immediately.

Need to add some checks somewhere?

**Comment by IHateMyKite** [comment]
I will give it a look. I think I have encountered this bug before, so it should be easy to replicate and fix.
