### ISSUE TITLE
UD patched items stop working for PC

### ISSUE THREAD

**Issue by kurotatsu77** [IHateMyKite/UnforgivingDevices#99]
Right now I'm running the most recent UD from GitHub with all scripts recompiled.
Skyrim LE, DD 5.2 beta 7.

I've noticed weird behavior, so went to test it out and found the following:
after equipping/removing UD patched DD devices about 20-30 times they stop equipping on PC, but continue to work on NPCs.
In the end to confirm it I've started new game and after setting all up simply started to add/remove items to reproduce the bug and got it. Also I've noticed higher chance of it happening if outfit has hood/gasmask in it, for example - colored catsuit Abadon outfits (applied with Abadon plug or concentrated black goo).

Maybe I need to somehow update DD UD patch? Do we have updated patching kit/instructions how to build it?

**Comment by kurotatsu77** [comment]
This is what ReSaver shows in the savegame after Concentrated Black Goo stopped working on mid-equip. 
It was rubber suit set which it tried to do, I think it was Gasmask which got it broken.

There are 99 stacks and 23 frames, which may indicate a problem.
[UD_CustomDevice_EquipScript](script://UD_CustomDevice_EquipScript) occurs the most often (8 occurrences)

**Comment by IHateMyKite** [comment]
I have fixed the issue, but didn't push it yet. Will push it once I will finish current work. Issue was that I have updated SwapDevice function in last version, which broke the whole Lock cycle.
